on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test PGXN Action
    steps:
      - uses: actions/checkout@v2
      - name: Setup PGXN Action
        uses: theory/pgxn-action@master
        with:
          postgresql password: test
      - run: env PGPASSWORD=test psql -U postgres -h localhost -c 'SELECT version()'
