on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: PGXN Action
      uses: theory/pgxn-action@v1
      with:
        postgresql password: test
    - name: Connect to PostgreSQL
      run: psql -U postgres -c 'SELECT version()'
